# Generated by Django 4.1.7 on 2023-03-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['id'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
